export const albums = [
    {
        title: "Let's Lament",
        category: "Album & Vinyl Record",
        year: 2024,
        cover: "/p90/covers/Let's Lament.jpg",
        link: "https://youtu.be/mGJ1HWhNU0g?si=-yFOzSo0eQRELobR",
    },
    {
        title: "Key Ingredient",
        category: "Album & Vinyl Record",
        year: 2022,
        cover: "/p90/covers/Key Ingredient.jpg",
        link: "https://linkco.re/M0BbScva",
    }, {
        title: "To Kill a Living Book",
        subtitle: "- for Library of Ruina -",
        category: "Album & Vinyl Record",
        year: 2021,
        cover: "/p90/covers/To Kill a Living Book.jpg",
        link: "https://linkco.re/RV9SAYan"
    }, {
        title: "Millennium Mother",
        category: "Album",
        year: 2018,
        cover: "/p90/covers/Millennium Mother.jpg",
        link: "https://mili.lnk.to/XXwbIWE",
    },
    {
        title: "Hue",
        category: "Album",
        year: 2017,
        cover: "/p90/covers/Hue.png",
        link: "https://mili.lnk.to/1ywrPWE",
    },
    {
        title: "Miracle Milk",
        category: "Album",
        year: 2016,
        cover: "/p90/covers/Miracle Milk.jpg",
        link: "https://mili.lnk.to/jJKqCWE",
    },
    {
        title: "Mag Mell",
        category: "Album",
        year: 2014,
        cover: "/p90/covers/Mag Mell.jpg",
        link: "https://mili.lnk.to/NBFKrWE",
    },
]

export const works = [
    {
        title: "铁花飞",
        subtitle: "Arknight",
        category: "Theme Song",
        year: 2026,
        cover: "/p90/covers/铁花飞.jpg",
        link: "https://youtu.be/acnx9QFbAp4?si=L3hO_OjOoypVBfS_",
    },
    {
        title: "Saikai",
        subtitle: "Limbus Company",
        category: "Theme Song",
        year: 2026,
        cover: "/p90/covers/Saikai.jpg",
        link: "https://youtu.be/h0djuhl97Kw?si=t34wcDqgAlfgbMLz",
    },
    {
        title: "What the Ripple Sees",
        subtitle: "Honkai: Star Rail",
        category: "Image Song",
        year: 2025,
        cover: "/p90/covers/What the Ripple Sees.jpg",
        link: "https://youtu.be/pLZAyjqu1F0?si=pe3Cmfi--HCW4ywi",
    },
    {
        title: "Tian Tian",
        subtitle: "Limbus Company",
        category: "Theme Song",
        year: 2025,
        cover: "/p90/covers/Tian Tian.jpg",
        link: "https://youtu.be/szyPY8nbBF4?si=ftBe9TpVHAftcZkG",
    },
    {
        title: "ENDER MAGNOLIA OST",
        subtitle: "Binary Haze Interactive",
        category: "Original Soundtrack",
        year: 2025,
        cover: "/p90/covers/Ender Magnolia Vinyl.jpg",
        link: "https://youtu.be/Nw9ubZeil84?si=S9imuNgsN6zZOpGR",
    },
    {
        title: "Year N",
        subtitle: "Promise of Wizard (魔法使いの約束)",
        category: "Theme Song",
        year: 2025,
        cover: "/p90/covers/Year N.jpg",
        link: "https://youtu.be/9t-uBxQzyXQ?si=bwCUQgIwQb3A9DE4",
    },
    // {
    //     title: "Process",
    //     subtitle: "Promise of Wizard (魔法使いの約束)",
    //     category: "Theme Song",
    //     year: 2024,
    //     cover: "/p90/covers/Mag Mell.jpg",
    //     link: "https://mili.lnk.to/NBFKrWE",
    // },
    // {
    //     title: "Life We Sow",
    //     subtitle: "Promise of Wizard (魔法使いの約束)",
    //     category: "Theme Song",
    //     year: 2024,
    //     cover: "/p90/covers/Mag Mell.jpg",
    //     link: "https://mili.lnk.to/NBFKrWE",
    // },
    // {
    //     title: "Monster in the Woods",
    //     subtitle: "Promise of Wizard (魔法使いの約束)",
    //     category: "Theme Song",
    //     year: 2024,
    //     cover: "/p90/covers/Mag Mell.jpg",
    //     link: "https://mili.lnk.to/NBFKrWE",
    // },
    // {
    //     title: "Gluttony",
    //     subtitle: "Promise of Wizard (魔法使いの約束)",
    //     category: "Theme Song",
    //     year: 2024,
    //     cover: "/p90/covers/Mag Mell.jpg",
    //     link: "https://mili.lnk.to/NBFKrWE",
    // },
    // {
    //     title: "Whiteout",
    //     subtitle: "Promise of Wizard (魔法使いの約束)",
    //     category: "Theme Song",
    //     year: 2024,
    //     cover: "/p90/covers/Mag Mell.jpg",
    //     link: "https://mili.lnk.to/NBFKrWE",
    // },
    // {
    //     title: "Hero",
    //     subtitle: "Limbus COmpany",
    //     category: "Theme Song",
    //     year: 2024,
    //     cover: "/p90/covers/Mag Mell.jpg",
    //     link: "https://mili.lnk.to/NBFKrWE",
    // },
    // {
    //     title: "Through Patches of Violet",
    //     subtitle: "Limbus COmpany",
    //     category: "Theme Song",
    //     year: 2024,
    //     cover: "/p90/covers/Mag Mell.jpg",
    //     link: "https://mili.lnk.to/NBFKrWE",
    // },
    // {
    //     title: "Grown-up's Paradise",
    //     subtitle: "Arknight",
    //     category: "Theme Song",
    //     year: 2024,
    //     cover: "/p90/covers/Mag Mell.jpg",
    //     link: "https://mili.lnk.to/NBFKrWE",
    // },
    // {
    //     title: "Duetting Solo",
    //     subtitle: "Goblin Slayer",
    //     category: "Theme Song",
    //     year: 2024,
    //     cover: "/p90/covers/Mag Mell.jpg",
    //     link: "https://mili.lnk.to/NBFKrWE",
    // },
    // {
    //     title: "Compass",
    //     subtitle: "Limbus Company",
    //     category: "Theme Song",
    //     year: 2023,
    //     cover: "/p90/covers/Mag Mell.jpg",
    //     link: "https://mili.lnk.to/NBFKrWE",
    // },
    // {
    //     title: "Entertianment",
    //     subtitle: "Goblin Slayer",
    //     category: "Theme Song",
    //     year: 2023,
    //     cover: "/p90/covers/Mag Mell.jpg",
    //     link: "https://mili.lnk.to/NBFKrWE",
    // },
    // {
    //     title: "Sleep Talk Metropolis",
    //     subtitle: "SONY",
    //     category: "Preinstalled Track",
    //     year: 2023,
    //     cover: "/p90/covers/Mag Mell.jpg",
    //     link: "https://mili.lnk.to/NBFKrWE",
    // },
    // {
    //     title: "Fly, My Wings",
    //     subtitle: "Limbus Company",
    //     category: "Theme Song",
    //     year: 2023,
    //     cover: "/p90/covers/Mag Mell.jpg",
    //     link: "https://mili.lnk.to/NBFKrWE",
    // },
    // {
    //     title: "Gunner in the Rain",
    //     subtitle: "DEEMO II",
    //     category: "Soundtrack",
    //     year: 2023,
    //     cover: "/p90/covers/Mag Mell.jpg",
    //     link: "https://mili.lnk.to/NBFKrWE",
    // },
    // {
    //     title: "Between Two Worlds",
    //     subtitle: "Limbus Company",
    //     category: "Theme Song",
    //     year: 2023,
    //     cover: "/p90/covers/Mag Mell.jpg",
    //     link: "https://mili.lnk.to/NBFKrWE",
    // },
    // {
    //     title: "Dancing Ghost's Ball Jointed Darling",
    //     subtitle: "NOIR DOLL (ノワールドール)",
    //     category: "Theme Song",
    //     year: 2022,
    //     cover: "/p90/covers/Mag Mell.jpg",
    //     link: "https://mili.lnk.to/NBFKrWE",
    // },
    // {
    //     title: "Mortal With You",
    //     subtitle: "Vermeil in Gold (金装のヴェルメイユ)",
    //     category: "Theme Song",
    //     year: 2022,
    //     cover: "/p90/covers/Mag Mell.jpg",
    //     link: "https://mili.lnk.to/NBFKrWE",
    // },
    // {
    //     title: "Paper Bouquet",
    //     subtitle: "The Executioner and Her Way of Life (処刑少女の生きる道)",
    //     category: "Theme Song",
    //     year: 2022,
    //     cover: "/p90/covers/Mag Mell.jpg",
    //     link: "https://mili.lnk.to/NBFKrWE",
    // },
    // {
    //     title: "Skin-Deep Comedy",
    //     subtitle: "Promise of Wizard (魔法使いの約束)",
    //     category: "Theme Song",
    //     year: 2022,
    //     cover: "/p90/covers/Mag Mell.jpg",
    //     link: "https://mili.lnk.to/NBFKrWE",
    // },
    // {
    //     title: "My Creator",
    //     subtitle: "Thy Creature",
    //     category: "Theme Song",
    //     year: 2022,
    //     cover: "/p90/covers/Mag Mell.jpg",
    //     link: "https://mili.lnk.to/NBFKrWE",
    // },
    // {
    //     title: "Sideshow Duckling",
    //     subtitle: "Welcome to Dreamland (欢迎来到梦乐园)",
    //     category: "Theme Song",
    //     year: 2022,
    //     cover: "/p90/covers/Mag Mell.jpg",
    //     link: "https://mili.lnk.to/NBFKrWE",
    // },
    // {
    //     title: "Dandelion Girl, Danelion Boy",
    //     subtitle: "Deemo II",
    //     category: "Soundtrack",
    //     year: 2022,
    //     cover: "/p90/covers/Mag Mell.jpg",
    //     link: "https://mili.lnk.to/NBFKrWE",
    // },
    // {
    //     title: "Bento Box Bivouac",
    //     subtitle: "Deemo II",
    //     category: "Soundtrack",
    //     year: 2022,
    //     cover: "/p90/covers/Mag Mell.jpg",
    //     link: "https://mili.lnk.to/NBFKrWE",
    // },
    // {
    //     title: "In Hell We Live, Lament",
    //     subtitle: "Limbus Company",
    //     category: "Theme Song",
    //     year: 2021,
    //     cover: "/p90/covers/Mag Mell.jpg",
    //     link: "https://mili.lnk.to/NBFKrWE",
    // },
    // {
    //     title: "Flowerwork",
    //     subtitle: "Promise of Wizard (魔法使いの約束)",
    //     category: "Theme Song",
    //     year: 2021,
    //     cover: "/p90/covers/Mag Mell.jpg",
    //     link: "https://mili.lnk.to/NBFKrWE",
    // },
    // {
    //     title: "ENDER LILIES OST",
    //     subtitle: "Binary Haze Interactive",
    //     category: "Original Soundtrack",
    //     year: 2021,
    //     cover: "/p90/covers/Mag Mell.jpg",
    //     link: "https://mili.lnk.to/NBFKrWE",
    // },
    // {
    //     title: "Ame to Taieki to Nioi",
    //     subtitle: "Gleipnir",
    //     category: "Theme Song",
    //     year: 2021,
    //     cover: "/p90/covers/Mag Mell.jpg",
    //     link: "https://mili.lnk.to/NBFKrWE",
    // },
    // {
    //     title: "Sustain++;",
    //     subtitle: "Ghost in the Shell: SAC_2045",
    //     category: "Theme Song",
    //     year: 2021,
    //     cover: "/p90/covers/Mag Mell.jpg",
    //     link: "https://youtu.be/JHY0PYZXvfU?si=sSvq8oDFCMreUsZP",
    // },
    // {
    //     title: "Static",
    //     subtitle: "Promise of Wizard (魔法使いの約束)",
    //     category: "Theme Song",
    //     year: 2021,
    //     cover: "/p90/covers/Mag Mell.jpg",
    //     link: "https://mili.lnk.to/NBFKrWE",
    // },
    // {
    //     title: "Cast Me a Spell",
    //     subtitle: "Limbus Company",
    //     category: "Theme Song",
    //     year: 2021,
    //     cover: "/p90/covers/Mag Mell.jpg",
    //     link: "https://mili.lnk.to/NBFKrWE",
    // },
    // {
    //     title: "Righfully",
    //     subtitle: "Goblin Slayer",
    //     category: "Theme Song",
    //     year: 2018,
    //     cover: "/p90/covers/Mag Mell.jpg",
    //     link: "https://mili.lnk.to/NBFKrWE",
    // },
    {
        title: "1000x1000",
        year: 2026,
        category: "single",
        cover: "/p90/covers/1000x1000.jpg",
        link: "https://youtu.be/sTyrH4SOwBY?si=b6UN_ndrFQBA4gTE",
    },
    {
        title: "Until Our Sky Is Blue",
        year: 2026,
        category: "single",
        cover: "/p90/covers/Until Our Sky Is Blue.jpg",
        link: "https://youtu.be/R1Ch963iuek?si=8eOE6UN_-zfjs3Kq",
    },
    {
        title: "Peach Pit and Cyanide",
        year: 2025,
        category: "Single",
        cover: "/p90/covers/Peach Pit and Cyanide.jpg",
        link: "https://youtu.be/cVL4bRjA6X0?si=-gv8DUs-w253utaY",
    },
    {
        title: "To Your Oblivion",
        year: 2025,
        category: "Single",
        cover: "/p90/covers/To Your Oblivion.jpg",
        link: "https://youtu.be/zVrHCm58N-o?si=lubzQvMubaqYRRNu",
    },
    {
        title: "I Am a Fluff",
        year: 2025,
        category: "Single",
        cover: "/p90/covers/I Am a Fluff.jpg",
        link: "https://youtu.be/emVNCcwCtuc?si=QJ609OQUoDXWJKHp",
    },
    {
        title: "Classroom Dreamer",
        year: 2025,
        category: "Single",
        cover: "/p90/covers/Classroom Dreamer.jpg",
        link: "https://youtu.be/dh57g0GMQWU?si=PduMut6eLSRGRhZL",
    },
    {
        title: "Bulbel",
        year: 2024,
        category: "Single",
        cover: "/p90/covers/Bulbel.jpg",
        link: "https://youtu.be/emVNCcwCtuc?si=QJ609OQUoDXWJKHp",
    },
    {
        title: "Dandelion Girls, Dandelion Boys",
        year: 2021,
        category: "Single",
        cover: "/p90/covers/Dandelion Girls, Dandelion Boys.jpg",
        link: "https://youtu.be/dh57g0GMQWU?si=PduMut6eLSRGRhZL",
    },
    {
        title: "E-01",
        year: 2019,
        category: "Single",
        cover: "/p90/covers/Hue.png",
        link: "https://youtu.be/emVNCcwCtuc?si=QJ609OQUoDXWJKHp",
    },
    {
        title: "Shitty Flowers",
        year: 2016,
        category: "Single",
        cover: "/p90/covers/Miracle Milk.jpg",
        link: "https://youtu.be/dh57g0GMQWU?si=PduMut6eLSRGRhZL",
    },
    {
        title: "幾年月",
        year: 2017,
        category: "Single",
        cover: "/p90/covers/幾年月.PNG",
        link: "https://youtu.be/emVNCcwCtuc?si=QJ609OQUoDXWJKHp",
    },
    {
        title: "Victim",
        year: 2018,
        category: "Single",
        cover: "/p90/covers/Victim.jpg",
        link: "https://youtu.be/dh57g0GMQWU?si=PduMut6eLSRGRhZL",
    },
    {
        title: "Nine Point Eight",
        year: 2014,
        category: "Single",
        cover: "/p90/covers/Nine Point Eight.PNG",
        link: "https://youtu.be/emVNCcwCtuc?si=QJ609OQUoDXWJKHp",
    },
    {
        title: "sustain++;",
        year: 2018,
        category: "Single",
        cover: "/p90/covers/Ghost In the Shell.PNG",
        link: "https://youtu.be/dh57g0GMQWU?si=PduMut6eLSRGRhZL",
    },
]

const singles = [

    {
        title: "Ocean Bby",
        year: 2023,
        category: "Single",
        cover: "/p90/covers/Mag Mell.jpg",
        link: "",
    },
    {
        title: "GIVE ME RICE",
        year: 2023,
        category: "Single",
        cover: "/p90/covers/Mag Mell.jpg",
        link: "",
    },
    {
        title: "Phantom Cat of Meowloween",
        year: 2019,
        category: "Single",
        cover: "/p90/covers/Mag Mell.jpg",
        link: "",
    },
    {
        title: "Birthday Kid",
        year: 2019,
        category: "Single",
        cover: "/p90/covers/Mag Mell.jpg",
        link: "",
    },
    {
        title: "Sloth",
        year: 2019,
        category: "Single",
        cover: "/p90/covers/Mag Mell.jpg",
        link: "",
    },
    {
        title: "不死蝶",
        year: 2019,
        category: "Single",
        cover: "/p90/covers/Mag Mell.jpg",
        link: "",
    },
    {
        title: "蜜蜂",
        year: 2019,
        category: "Single",
        cover: "/p90/covers/Mag Mell.jpg",
        link: "",
    },
    {
        title: "Victim",
        year: 2019,
        category: "Single",
        cover: "/p90/covers/Mag Mell.jpg",
        link: "",
    },
]

// export default Constants;